name: GenAI_OpenStack_RCA CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # - name: Log in to DockerHub
    #   run: |
    #     echo "dckr_pat_LqvpR0mlz4tBV3f6pvV77w01JtQ" | docker login -u "aimlc3sudipto" --password-stdin

    # - name: Enable Docker Debugging
    #   run: |
    #     export DOCKER_CLI_DEBUG=1
    #     echo "dckr_pat_LqvpR0mlz4tBV3f6pvV77w01JtQ" | docker login -u "aimlopscsudipto@gmail.com" --password-stdin
    #     docker build . \
    #       --file Dockerfile \
    #       --tag aimlc3sudipto/genai_openstack_rca:latest \
    #       --tag aimlc3sudipto/genai_openstack_rca:$(date +%Y%m%d%H%M%S)
    #     docker push aimlc3sudipto/genai_openstack_rca:latest
    #     docker push aimlc3sudipto/genai_openstack_rca:$(date +%Y%m%d%H%M%S)

    # - name: Push Docker Image debug
    #   run: |
    #     docker tag hello-world aimlopscsudipto/hello-world:latest
    #     docker push aimlopscsudipto/hello-world:latest
    #     docker push aimlopscsudipto/genai_openstack_rca:latest
    #     docker push aimlopscsudipto/genai_openstack_rca:$(date +%Y%m%d%H%M%S)

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        # username: aimlopscsudipto@gmail.com
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build Docker Image
    #   run: |
    #     docker build . \
    #       --file Dockerfile \
    #       --tag aimlopscsudipto/genai_openstack_rca:latest \
    #       --tag aimlopscsudipto/genai_openstack_rca:$(date +%Y%m%d%H%M%S)
    # - name: Push Docker Image
    #   run: |
    #     docker push aimlopscsudipto/genai_openstack_rca:latest
    #     docker push aimlopscsudipto/genai_openstack_rca:$(date +%Y%m%d%H%M%S)
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   - name: Login to DockerHub
  #     run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u aimlopscsudipto@gmail.com --password-stdin

  #   - name: Pull Docker Image
  #     run: docker pull aimlopscsudipto/genai_openstack_rca:latest

  #   - name: Deploy to AWS
  #     env:
  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  #     run: |
  #       # Stop existing container if running
  #       docker rm -f genai-openstack-container || true
  #       # Run new container
  #       docker run -d \
  #         -p 8000:8000 \
  #         --name genai-openstack-container \
  #         ${{ secrets.DOCKER_USERNAME }}/genai_openstack_rca:latest
